### ISSUE TITLE
add Memcached support

### ISSUE THREAD

**Issue by erichuang2015** [antonlukin/notset#3]
Hello

would you plan to support Memcached ? 

thanks

**Comment by antonlukin** [comment]
Hello,
why do you think it can be useful?

**Comment by erichuang2015** [comment]
For some extensions, requests are limited. 

If not cached, when someone sends 100+ requests for the same domain in a short time, registry will block the ip, so the whois services will stop.

What's more, when cached, users will get results fast instead of querying the registry servers.

I do hope there is an option to enable cache in this app

**Comment by antonlukin** [comment]
Doesn't make sense now. Just use whois utility
